Keep the error messages visible
celo-org/snark-setup-operator pull request #37
Opened 2020-12-21 11:03 UTC by mrsmkl

Should help with #34

2020-12-23 04:31 UTC, kobigurk requested changes

2020-12-23 04:31 UTC, kobigurk commented on src/bin/contribute.rs
> +                        progress_bar.println(&format!(
What happens if the message is long?
For the `set_message`, we used the format string to set it to not overflow and keep printing the same line over and over.
What will happen here?

2020-12-23 04:31 UTC, kobigurk commented on src/bin/contribute.rs
> +            let progress_bar2 = progress_bar3.clone();
```suggestion
            let progress_bar_for_thread = progress_bar3.clone();
```

2020-12-23 04:31 UTC, kobigurk commented on src/bin/contribute.rs
> +                            progress_bar2
```suggestion
                            progress_bar_for_thread 
```

2020-12-23 04:31 UTC, kobigurk commented on src/bin/contribute.rs
> +        let progress_bar3 = progress_bar.clone();
```suggestion
        let progress_bar_for_thread = progress_bar.clone();
```

2020-12-23 04:31 UTC, kobigurk commented on src/bin/contribute.rs
> +                        progress_bar.println(&format!(
```suggestion
                        progress_bar_for_thread.println(&format!(
```

2020-12-23 11:05 UTC, mrsmkl commented on src/bin/contribute.rs
> +                        progress_bar.println(&format!(
It will just print the message once, but I guess it would get truncated.

2020-12-23 11:59 UTC, kobigurk commented on src/bin/contribute.rs
> +                        progress_bar.println(&format!(
The experience we had with `set_message` is that it wasn't truncated by default, it kept printing the same message over and over. I suggest we check that for println...

2020-12-23 12:06 UTC, mrsmkl commented on src/bin/contribute.rs
> +                        progress_bar.println(&format!(
Here's what it looks like (I have a timer that calls `progress_bar.println` each 20 seconds):
```
Contributing! Please unmount and remove the USB drive containing your keys now.
sddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
sddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
sddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
⠐ [00:00:50] [####################] 8/8 Successfully contributed! Don't turn this off yet, you might still be needed. Thank you for participating!
```

2020-12-23 12:14 UTC, kobigurk commented on src/bin/contribute.rs
> +                        progress_bar.println(&format!(
OK, that looks good! So the overflow just prints the message once, and doesn't even truncate?

2020-12-23 12:28 UTC, mrsmkl commented on src/bin/contribute.rs
> +                        progress_bar.println(&format!(
Yeah, correct.

2020-12-25 16:38 UTC, kobigurk approved these changes

2020-12-29 12:38 UTC, merged